# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages


# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      language: cpp
      sudo: required
      dist: trusty
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=trusty_clang
        - DETAILS="optimized build, no libtool"
    - osx_image: xcode8
      language: objective-c
      compiler: clang
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=osx
        - DETAILS="debug build, libtool"

before_install:
  - cd
  - wget http://download.osgeo.org/gdal/2.2.3/gdal-2.2.3.tar.gz
  - wget http://download.osgeo.org/gdal/2.2.3/gdalautotest-2.2.3.tar.gz
  - tar zxf gdal-2.2.3.tar.gz
  - tar zxf gdalautotest-2.2.3.tar.gz
  - mv gdal-2.2.3 gdal
  - mv gdalautotest-2.2.3 autotest
  - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./gdal/ci/travis/${BUILD_NAME}/install.sh

## don't run the tests, MDSumner Feb 2018
#script:
  - ./gdal/ci/travis/${BUILD_NAME}/script.sh

after_success:
    - Rscript -e 'covr::codecov()'

